#pragma once
#include "flprogBoardInfoESP32.h"
#ifdef ARDUINO_ARCH_ESP32
#if (CONFIG_IDF_TARGET_ESP32C3 || CONFIG_IDF_TARGET_ESP32S3)
#if ARDUINO_USB_CDC_ON_BOOT
#define FLPROG_HAS_UART0 "USB UART0 USBSerial"
#else
#define FLPROG_HAS_UART0 "USB UART0 Serial"
#ifdef SOC_TX0
#define FLPROG_UART0_TX SOC_TX0
#if CONFIG_IDF_TARGET_ESP32
#define FLPROG_UART0_TX 1
#elif CONFIG_IDF_TARGET_ESP32S2 || CONFIG_IDF_TARGET_ESP32S3
#define FLPROG_UART0_TX 43
#elif CONFIG_IDF_TARGET_ESP32C3
#define FLPROG_UART0_TX 21
#endif
#endif
#ifdef SOC_RX0
#define FLPROG_UART0_RX SOC_RX0
#else
#if CONFIG_IDF_TARGET_ESP32
#define FLPROG_UART0_RX 3
#elif CONFIG_IDF_TARGET_ESP32S2 || CONFIG_IDF_TARGET_ESP32S3
#define FLPROG_UART0_RX 44
#elif CONFIG_IDF_TARGET_ESP32C3
#define FLPROG_UART0_RX 20
#endif
#endif
#endif
#else
#if CONFIG_TINYUSB_CDC_ENABLED
#define FLPROG_HAS_UART0 "USB UART USBSerial"
#endif
#endif

#if SOC_UART_NUM > 1
#define FLPROG_HAS_UART1 "Hardware UART1 Serial1"

#ifdef TX1
#define FLPROG_UART1_TX TX1
#else
#if CONFIG_IDF_TARGET_ESP32
#define FLPROG_UART1_TX 10
#elif CONFIG_IDF_TARGET_ESP32S2
#define FLPROG_UART1_TX 17
#elif CONFIG_IDF_TARGET_ESP32C3
#define FLPROG_UART1_TX 19
#elif CONFIG_IDF_TARGET_ESP32S3
#define FLPROG_UART1_TX 16
#endif
#endif

#ifdef RX1
#define FLPROG_UART1_RX RX1
#else
#if CONFIG_IDF_TARGET_ESP32
#define FLPROG_UART1_RX 9
#elif CONFIG_IDF_TARGET_ESP32S2
#define FLPROG_UART1_RX 18
#elif CONFIG_IDF_TARGET_ESP32C3
#define FLPROG_UART1_RX 18
#elif CONFIG_IDF_TARGET_ESP32S3
#define FLPROG_UART1_RX 15
#endif
#endif
#endif

#if SOC_UART_NUM > 2
#define FLPROG_HAS_UART2 "Hardware UART2 Serial2"
#ifdef TX2
#define FLPROG_UART2_TX TX2
#else
#if CONFIG_IDF_TARGET_ESP32
#define FLPROG_UART2_TX 17
#elif CONFIG_IDF_TARGET_ESP32S3
#define FLPROG_UART2_TX 20
#endif
#endif

#ifdef RX2
#define FLPROG_UART2_RX RX2
#else
#if CONFIG_IDF_TARGET_ESP32
#define FLPROG_UART2_RX 16
#elif CONFIG_IDF_TARGET_ESP32S3
#define FLPROG_UART2_RX 19
#endif
#endif
#endif

#endif
