#pragma once
#include "flprogBoardInfoRP240.h"

#ifdef ARDUINO_ARCH_RP2040
#define FLPROG_HAS_SPI0
#define FLPROG_SPI0_MISO PIN_SPI0_MISO
#define FLPROG_SPI0_MOSI PIN_SPI0_MOSI
#define FLPROG_SPI0_SCK PIN_SPI0_SCK
#define FLPROG_SPI0_SS PIN_SPI0_SS
#define FLPROG_HAS_SPI1
#define FLPROG_SPI1_MISO PIN_SPI1_MISO
#define FLPROG_SPI1_MOSI PIN_SPI1_MOSI
#define FLPROG_SPI1_SCK PIN_SPI1_SCK
#define FLPROG_SPI1_SS PIN_SPI1_SS
#endif